%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam;
imu: 1
num_of_cam: 2
imu_topic: "/imu/data_raw"
image0_topic: "/stereo/left/image_raw"
image1_topic: "/stereo/right/image_raw"
output_path: "/home/sy/sy/vins_fusion_ws/src/VINS-Fusion/output/KAIST"
cam0_calib: "cam0_pinhole.yaml"
cam1_calib: "cam1_pinhole.yaml"
image_width: 1280
image_height: 560
focal_length: 811
init_depth: 5.0
# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1 # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
# 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [-0.00681, -0.01532, 0.99987, 1.71239, -0.99998, 0.00033, -0.00680, 0.24740, -0.00023, -0.99988, -0.01532, -0.11589, 0.00000, 0.00000, 0.00000, 1.00000]
body_T_cam1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [-0.00373, -0.01192, 0.99993, 1.70555, -0.99999, -0.00158, -0.00375, -0.23408, 0.00162, -0.99993, -0.01192, -0.11617, 0.00000, 0.00000, 0.00000, 1.00000]
#body_T_cam0: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [ -0.00413,-0.01966,0.99980,1.73944,
#           -0.99993,-0.01095,-0.00435,0.27803,
#           0.01103,-0.99975,-0.01962,-0.08785,
#           0.00000,0.00000,0.00000,1.00000]
#
#body_T_cam1: !!opencv-matrix
#   rows: 4
#   cols: 4
#   dt: d
#   data: [ -0.00768,-0.01509,0.99986,1.73376,
#           -0.99988,-0.01305,-0.00788,-0.19706,
#           0.01317,-0.99980,-0.01499,-0.08271,
#           0.00000,0.00000,0.00000,1.00000]

#Multiple thread support
multiple_thread: 1
#feature traker paprameters
max_cnt: 250 # 250 max feature number in feature tracking
min_dist: 25 # 20 min distance between two features
freq: 0 # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 2.5 # ransac threshold (pixel)
show_track: 1 # publish tracking image as topic
flow_back: 1 # perform forward and backward optical flow to improve feature tracking accuracy
#optimization parameters
max_solver_time: 0.08 # max solver itration time (ms), to guarantee real time
max_num_iterations: 8 # 8 max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1 # accelerometer measurement noise standard deviation.
gyr_n: 0.001 # 0.001 gyroscope measurement noise standard deviation.
acc_w: 0.001 # accelerometer bias random work noise standard deviation.
gyr_w: 0.0001 # gyroscope bias random work noise standard deviation.
g_norm: 9.81007 # gravity magnitude
#unsynchronization parameters
estimate_td: 1 # online estimate time offset between camera and imu
td: -0.005 # -0.005 initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)
#loop closure parameters
load_previous_pose_graph: 0 # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "/media/sy/data1/sy/vins_pose_graph" # save and load path
save_image: 0 # save image in pose graph for visualization prupose; you can close this function by setting 0
PNP_INFLATION: 4.0
height_adj: 560
width_adj: 1280
USE_SP: 1
MIN_LOOP_NUM: 20
loop_top_thres: 0.55
loop_back_thres: 0.50
MAX_THETA_DIFF: 90.0
MAX_POSE_DIFF: 40.0
USE_BAG_LOAD: 1
FAST_BAG: 1
F_BAG_PATH: /media/sy/data2/datasets/KAIST/camera/bag/39.bag
